# Generated by Django 5.0.6 on 2024-06-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona', verbose_name='Persona'),
        ),
    ]
