# Generated by Django 5.0.6 on 2024-06-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_afp', models.CharField(max_length=45, verbose_name='Nombre de AFP')),
                ('codigo_afp', models.CharField(max_length=2, unique=True, verbose_name='Código de AFP')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AFP',
                'verbose_name_plural': 'AFPs',
                'db_table': 'afp',
                'ordering': ['nombre_afp'],
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=45, verbose_name='Nombre de Banco')),
                ('codigo_banco', models.CharField(max_length=3, unique=True, verbose_name='Código de Banco')),
                ('abreviatura_banco', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'banco',
                'ordering': ['nombre_banco'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=45, verbose_name='Nombre de Cargo')),
                ('codigo_cargo', models.CharField(max_length=3, unique=True, verbose_name='Código de Cargo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['nombre_cargo'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoRemunerativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45, verbose_name='Tipo(Si es Haber o Descuento)')),
                ('codigo_mcpp', models.CharField(max_length=4, unique=True, verbose_name='Código MCPP Web')),
                ('codigo_plame', models.CharField(max_length=4, verbose_name='Código Plame')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción de la Norma')),
                ('imponible', models.BooleanField(default=False, verbose_name='Es Imponible?')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estado_civil', models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Código de Estado Civil')),
                ('nombre_estado_civil', models.CharField(max_length=45, verbose_name='Nombre de Estado Civil')),
                ('abreviatura_estado_civil', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
                'db_table': 'estado_civil',
                'ordering': ['nombre_estado_civil'],
            },
        ),
        migrations.CreateModel(
            name='FuenteFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente_financiamiento', models.CharField(blank=True, max_length=45, verbose_name='Nombre de Fuente de Financiamiento')),
                ('codigo_fuente_financiamiento', models.CharField(blank=True, max_length=2, unique=True, verbose_name='Código de Fuente de Financiamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuente de Financiamiento',
                'verbose_name_plural': 'Fuentes de Financiamiento',
                'db_table': 'fuente_financiamiento',
                'ordering': ['nombre_fuente_financiamiento'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=True, max_length=2, verbose_name='Mes')),
                ('anio', models.CharField(blank=True, max_length=4, verbose_name='Año')),
                ('periodo', models.CharField(blank=True, editable=False, max_length=6, unique=True, verbose_name='Periodo')),
                ('es_adicional', models.BooleanField(default=False, verbose_name='¿Es adicional?')),
                ('periodo_actual', models.CharField(blank=True, default=None, editable=False, max_length=6, null=True, verbose_name='Periodo Actual')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'db_table': 'periodo',
                'ordering': ['anio', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='RegimenLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_regimen_laboral', models.CharField(max_length=45, verbose_name='Nombre de Régimen Laboral')),
                ('codigo_regimen_laboral', models.CharField(max_length=2, unique=True, verbose_name='Código de Régimen Laboral')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Régimen Laboral',
                'verbose_name_plural': 'Regímenes Laborales',
                'db_table': 'regimen_laboral',
                'ordering': ['nombre_regimen_laboral'],
            },
        ),
        migrations.CreateModel(
            name='RegimenPensionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_regimen_pensionario', models.CharField(max_length=45, verbose_name='Nombre de Régimen Pensionario')),
                ('codigo_regimen_pensionario', models.CharField(max_length=2, unique=True, verbose_name='Código de Régimen Pensionario')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Régimen Pensionario',
                'verbose_name_plural': 'Regímenes Pensionarios',
                'db_table': 'regimen_pensionario',
                'ordering': ['nombre_regimen_pensionario'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sexo', models.CharField(max_length=1, unique=True, verbose_name='Código')),
                ('descripcion_sexo', models.CharField(max_length=20, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'db_table': 'sexo',
                'ordering': ['descripcion_sexo'],
            },
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_situacion', models.CharField(max_length=45, verbose_name='Nombre de Situación')),
                ('abreviatura_situacion', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('codigo_situacion', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Situación',
                'verbose_name_plural': 'Situaciones',
                'db_table': 'situacion',
                'ordering': ['nombre_situacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tipo_beneficiario', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('descripcion_tipo_beneficiario', models.CharField(max_length=20, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Beneficiario',
                'verbose_name_plural': 'Tipos de Beneficiario',
                'db_table': 'tipo_beneficiario',
                'ordering': ['descripcion_tipo_beneficiario'],
            },
        ),
        migrations.CreateModel(
            name='TipoDeCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tipo_descuento', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('descripcion_tipo_descuento', models.CharField(max_length=20, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Descuento',
                'verbose_name_plural': 'Tipos de Descuento',
                'db_table': 'tipo_descuento',
                'ordering': ['descripcion_tipo_descuento'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tipo_documento', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('descripcion_tipo_documento', models.CharField(max_length=50, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipo_documento',
                'ordering': ['descripcion_tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='TipoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_planilla', models.CharField(blank=True, max_length=45, verbose_name='Nombre de Tipo de Planilla')),
                ('codigo_tipo_planilla', models.CharField(blank=True, max_length=2, unique=True, verbose_name='Código de Tipo de Planilla')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Planilla',
                'verbose_name_plural': 'Tipos de Planilla',
                'db_table': 'tipo_planilla',
                'ordering': ['nombre_tipo_planilla'],
            },
        ),
        migrations.CreateModel(
            name='TipoRegistroAirhsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_servidor', models.CharField(max_length=45, verbose_name='Nombre de Tipo de Servidor')),
                ('codigo_tipo_servidor', models.CharField(max_length=2, unique=True, verbose_name='Código de Tipo de Servidor')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servidor',
                'verbose_name_plural': 'Tipos de Servidores',
                'db_table': 'tipo_servidor',
                'ordering': ['nombre_tipo_servidor'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(choices=[('HABER', 'Haber'), ('DESCUENTO', 'Descuento')], default='HABER', max_length=10, verbose_name='Tipo')),
                ('codigo_transaccion_mcpp', models.CharField(help_text='Código MCPP', max_length=4, unique=True, verbose_name='Código MCPP')),
                ('codigo_transaccion_plame', models.CharField(help_text='Codigo PLAME', max_length=4, unique=True, verbose_name='Codigo PLAME')),
                ('descripcion_transaccion', models.CharField(max_length=45, verbose_name='Descripción')),
                ('imponible', models.BooleanField(default=False, verbose_name='Es Imponible?')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transaccion',
                'ordering': ['descripcion_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='Ugel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ugel', models.CharField(max_length=100, verbose_name='Nombre de UGEL')),
                ('nombre_corto_ugel', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre Corto de UGEL')),
                ('codigo_ugel', models.CharField(max_length=6, unique=True, verbose_name='Código de Ugel')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UGEL',
                'verbose_name_plural': 'UGELs',
                'db_table': 'ugel',
                'ordering': ['nombre_ugel'],
            },
        ),
        migrations.CreateModel(
            name='ClasePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase_planilla', models.CharField(blank=True, max_length=45, verbose_name='Nombre de Clase de Planilla')),
                ('codigo_clase_planilla', models.CharField(blank=True, max_length=2, unique=True, verbose_name='Código de Clase de Planilla')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_planilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.tipoplanilla', verbose_name='Tipo de Planilla')),
            ],
            options={
                'verbose_name': 'Clase de Planilla',
                'verbose_name_plural': 'Clases de Planilla',
                'db_table': 'clase_planilla',
                'ordering': ['nombre_clase_planilla'],
            },
        ),
    ]
