# Generated by Django 5.0.6 on 2024-06-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='categoria_transaccion',
            field=models.CharField(choices=[('SUELDO', 'Sueldo'), ('BONIFICACION', 'Bonificación'), ('DEDUCCION', 'Deducción'), ('BENEFICIOS_SOCIALES', 'Beneficios Sociales'), ('APORTE', 'Aporte'), ('OTRO', 'Otro')], default='SUELDO', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_transaccion',
            field=models.CharField(choices=[('HABER', 'Haber'), ('DESCUENTO', 'Descuento'), ('APORTE', 'Aporte')], default='HABER', max_length=10, verbose_name='Tipo'),
        ),
    ]
