# Generated by Django 5.0.6 on 2024-06-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_transaccion_categoria_transaccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugel',
            name='codigo_ugel',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código de Ugel'),
        ),
    ]
