# Generated by Django 5.0.6 on 2024-07-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_alter_ugel_codigo_ugel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionAfp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_flujo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Comisión por Flujo')),
                ('comision_mixta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Comisión Mixta')),
                ('prima_seguro', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prima de Seguro')),
                ('aporte_obligatorio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Aporte Obligatorio')),
                ('total_comision', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Comisión')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.periodo', verbose_name='Periodo')),
                ('afp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.afp', verbose_name='AFP')),
            ],
            options={
                'verbose_name': 'Comisión AFP',
                'verbose_name_plural': 'Comisiones AFP',
                'db_table': 'comision_afp',
                'ordering': ['Periodo'],
            },
        ),
    ]
