# Generated by Django 5.0.6 on 2024-07-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_comisionafp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comisionafp',
            options={'ordering': ['periodo'], 'verbose_name': 'Comisión AFP', 'verbose_name_plural': 'Comisiones AFP'},
        ),
        migrations.RenameField(
            model_name='comisionafp',
            old_name='Periodo',
            new_name='periodo',
        ),
    ]
