# Generated by Django 5.0.6 on 2024-07-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_alter_comisionafp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
