# Generated by Django 5.0.6 on 2024-07-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_periodo_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['periodo', 'es_adicional'], 'verbose_name': 'Período', 'verbose_name_plural': 'Períodos'},
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='periodo_actual',
        ),
    ]
