# Generated by Django 5.0.6 on 2024-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_alter_periodo_options_remove_periodo_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionafp',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
