# Generated by Django 5.0.6 on 2024-07-15 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_comisionafp_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo_dato', models.CharField(choices=[('NUMERIC', 'Numérico'), ('TEXT', 'Texto'), ('JSON', 'JSON'), ('BOOLEAN', 'Booleano'), ('DATE', 'Fecha')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ValorConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='comisionafp',
            index=models.Index(fields=['periodo', 'afp'], name='idx_comisionafp_periodo_afp'),
        ),
        migrations.AddIndex(
            model_name='periodo',
            index=models.Index(fields=['periodo', 'estado'], name='idx_periodo_estado'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['codigo_transaccion_mcpp'], name='idx_transaccion_codigo_mcpp'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo_transaccion'], name='idx_transaccion_tipo'),
        ),
        migrations.AddIndex(
            model_name='ugel',
            index=models.Index(fields=['codigo_ugel'], name='idx_ugel_codigo'),
        ),
        migrations.AddField(
            model_name='valorconfiguracionglobal',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='configuracion.configuracionglobal'),
        ),
        migrations.AddField(
            model_name='valorconfiguracionglobal',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
