# Generated by Django 5.0.6 on 2024-07-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_configuracionglobal_valorconfiguracionglobal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorconfiguracionglobal',
            name='norma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
