# Generated by Django 5.0.6 on 2024-06-27 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase_planilla', models.CharField(blank=True, max_length=45, verbose_name='Nombre de Clase de Planilla')),
                ('codigo_clase_planilla', models.CharField(blank=True, max_length=2, verbose_name='Código de Clase de Planilla')),
            ],
            options={
                'verbose_name': 'Clase de Planilla',
                'verbose_name_plural': 'Clases de Planilla',
                'db_table': 'clase_planilla',
                'ordering': ['nombre_clase_planilla'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=True, max_length=2, verbose_name='Mes')),
                ('anio', models.CharField(blank=True, max_length=4, verbose_name='Año')),
                ('periodo', models.CharField(blank=True, editable=False, max_length=6, verbose_name='Periodo')),
                ('es_adicional', models.BooleanField(default=False, verbose_name='¿Es adicional?')),
                ('periodo_actual', models.CharField(blank=True, default=None, editable=False, max_length=6, null=True, verbose_name='Periodo Actual')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'db_table': 'periodo',
                'ordering': ['anio', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='PlanillaBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Planilla del Beneficiario',
                'verbose_name_plural': 'Planillas de los Beneficiarios',
                'db_table': 'planilla_beneficiario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlanillaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_haberes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total de Haberes')),
                ('total_descuentos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total de Descuentos')),
                ('essalud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ESSALUD')),
                ('emitio_boleta', models.SmallIntegerField(blank=True, null=True, verbose_name='Emisión de Boleta')),
            ],
            options={
                'verbose_name': 'Planilla del Trabajador',
                'verbose_name_plural': 'Planillas de los Trabajadores',
                'db_table': 'planilla_trabajador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_planilla', models.CharField(blank=True, max_length=45, verbose_name='Nombre de Tipo de Planilla')),
                ('codigo_tipo_planilla', models.CharField(blank=True, max_length=2, verbose_name='Código de Tipo de Planilla')),
            ],
            options={
                'verbose_name': 'Tipo de Planilla',
                'verbose_name_plural': 'Tipos de Planilla',
                'db_table': 'tipo_planilla',
                'ordering': ['nombre_tipo_planilla'],
            },
        ),
        migrations.CreateModel(
            name='FuenteFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente_financiamiento', models.CharField(blank=True, max_length=45, verbose_name='Nombre de Fuente de Financiamiento')),
                ('tipo_planilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planillas.claseplanilla', verbose_name='Clase de Planilla')),
            ],
            options={
                'verbose_name': 'Fuente de Financiamiento',
                'verbose_name_plural': 'Fuentes de Financiamiento',
                'db_table': 'fuente_financiamiento',
                'ordering': ['nombre_fuente_financiamiento'],
            },
        ),
    ]
