# Generated by Django 5.0.6 on 2024-06-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(max_length=10, verbose_name='Correlativo')),
                ('total_haberes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Haberes')),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Descuentos')),
                ('total_aportes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Aportes')),
                ('estado', models.CharField(choices=[('APERTURADO', 'Aperturado'), ('CERRADO', 'Cerrado')], default='APERTURADO', max_length=10, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanillaBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Planilla del Beneficiario',
                'verbose_name_plural': 'Planillas de los Beneficiarios',
                'db_table': 'planilla_beneficiario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='Fecha de Cese')),
                ('documento_contrato', models.CharField(blank=True, max_length=45, verbose_name='Documento de Contrato')),
                ('documento_cese', models.CharField(blank=True, max_length=45, verbose_name='Documento de Cese')),
                ('dias_laborados', models.IntegerField(blank=True, default=30, null=True, verbose_name='Días Laborados')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.cargo', verbose_name='Cargo')),
                ('clase_planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.claseplanilla', verbose_name='Clase de Planilla')),
                ('fuente_financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.fuentefinanciamiento', verbose_name='Fuente de Financiamiento')),
                ('regimen_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.regimenlaboral', verbose_name='Régimen Laboral')),
                ('situacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.situacion', verbose_name='Situación')),
                ('tipo_servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.tiposervidor', verbose_name='Tipo de Servidor')),
            ],
            options={
                'verbose_name': 'Contrato del Trabajador',
                'verbose_name_plural': 'Contratos de los Trabajadores',
                'db_table': 'contrato',
                'ordering': ['id'],
            },
        ),
    ]
