# Generated by Django 5.0.6 on 2024-06-27 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planillas', '0001_initial'),
        ('trabajadores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillabeneficiario',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario'),
        ),
        migrations.AddField(
            model_name='planillabeneficiario',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planillas.periodo', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='planillatrabajador',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planillas.periodo', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='planillatrabajador',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remuneraciones', to='trabajadores.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='planillatrabajador',
            name='ugel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ugel', verbose_name='UGEL'),
        ),
        migrations.AddField(
            model_name='planillatrabajador',
            name='tipo_planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planillas.tipoplanilla', verbose_name='Tipo de Planilla'),
        ),
        migrations.AddField(
            model_name='claseplanilla',
            name='tipo_planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planillas.tipoplanilla', verbose_name='Tipo de Planilla'),
        ),
    ]
