# Generated by Django 5.0.6 on 2024-06-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('planillas', '0001_initial'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='trabajadores.trabajador'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='clase_planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.claseplanilla', verbose_name='Clase de Planilla'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='contratos',
            field=models.ManyToManyField(blank=True, related_name='planillas', to='planillas.contrato'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='fuente_financiamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.fuentefinanciamiento', verbose_name='Fuente de Financiamiento'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.periodo', verbose_name='Período'),
        ),
    ]
