# Generated by Django 5.0.6 on 2024-06-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0002_initial'),
        ('trabajadores', '0003_situacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='Fecha de Cese')),
                ('documento_contrato', models.CharField(blank=True, max_length=45, verbose_name='Documento de Contrato')),
                ('documento_cese', models.CharField(blank=True, max_length=45, verbose_name='Documento de Cese')),
                ('dias_laborados', models.IntegerField(blank=True, default=30, null=True, verbose_name='Días Laborados')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.cargo', verbose_name='Cargo')),
                ('clase_planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planillas.claseplanilla', verbose_name='Clase de Planilla')),
                ('fuente_financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planillas.fuentefinanciamiento', verbose_name='Fuente de Financiamiento')),
                ('regimen_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.regimenlaboral', verbose_name='Régimen Laboral')),
                ('situacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.situacion', verbose_name='Situación')),
                ('tipo_servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.tiposervidor', verbose_name='Tipo de Servidor')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='trabajadores.trabajador')),
            ],
            options={
                'verbose_name': 'Contrato del Trabajador',
                'verbose_name_plural': 'Contratos de los Trabajadores',
                'db_table': 'contrato',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='PlanillaTrabajador',
        ),
    ]
