# Generated by Django 5.0.6 on 2024-06-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('planillas', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillabeneficiario',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario'),
        ),
        migrations.AddField(
            model_name='planillabeneficiario',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.periodo', verbose_name='Período'),
        ),
        migrations.AlterUniqueTogether(
            name='planilla',
            unique_together={('correlativo', 'periodo')},
        ),
    ]
