# Generated by Django 5.0.6 on 2024-06-30 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='contratos',
        ),
        migrations.AlterModelTable(
            name='planilla',
            table='planilla',
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_haberes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Haberes')),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Descuentos')),
                ('total_aportes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Aportes')),
                ('neto_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto a Pagar')),
                ('numero_boleta', models.CharField(max_length=5, verbose_name='Número de Boleta')),
                ('visualizada', models.BooleanField(default=False, verbose_name='Visualizada')),
                ('fecha_visualizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Visualización')),
                ('descargada', models.BooleanField(default=False, verbose_name='Descargada')),
                ('fecha_descarga', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Descarga')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='planillas.contrato')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='planillas.planilla')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'db_table': 'boleta',
                'ordering': ['planilla', 'contrato'],
                'unique_together': {('contrato', 'planilla')},
            },
        ),
    ]
