# Generated by Django 5.0.6 on 2024-06-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0004_remove_planilla_contratos_alter_planilla_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['id'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AddField(
            model_name='contrato',
            name='centro_de_trabajo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Centro de Trabajo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='jornada_laboral',
            field=models.IntegerField(blank=True, default=48, null=True, verbose_name='Jornada Laboral'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='leyenda_permanente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Leyenda Permanente'),
        ),
    ]
