# Generated by Django 5.0.6 on 2024-07-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0006_alter_boleta_descargada_alter_boleta_fecha_descarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='numero_boleta',
            field=models.CharField(editable=False, max_length=3, verbose_name='Número de Boleta'),
        ),
    ]
