# Generated by Django 5.0.6 on 2024-07-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0007_alter_boleta_numero_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='sueldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sueldo'),
        ),
    ]
