# Generated by Django 5.0.6 on 2024-07-02 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0008_contrato_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='banco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='centro_de_trabajo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Centro de Trabajo'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='clase_planilla',
            field=models.CharField(blank=True, max_length=255, verbose_name='Clase de Planilla'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cuenta Bancaria'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='dias_laborados',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Días Laborados'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='fecha_cese',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cese'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='fuente_financiamiento',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fuente de Financiamiento'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='jornada_laboral',
            field=models.IntegerField(blank=True, default=48, null=True, verbose_name='Jornada Laboral'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='leyenda_permanente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Leyenda Permanente'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='regimen_laboral',
            field=models.CharField(blank=True, max_length=255, verbose_name='Régimen Laboral'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='regimen_pensionario',
            field=models.CharField(blank=True, max_length=255, verbose_name='Régimen Pensionario'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='sueldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sueldo'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='tipo_servidor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tipo de Servidor'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='trabajador_apellidos',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Apellidos del Trabajador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='trabajador_dni',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='DNI del Trabajador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='trabajador_nombres',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Nombres del Trabajador'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BoletaTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Transacción')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Transacción')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción de Transacción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='planillas.boleta')),
            ],
            options={
                'verbose_name': 'Boleta Transacción',
                'verbose_name_plural': 'Boleta Transacciones',
                'db_table': 'boleta_transacciones',
            },
        ),
    ]
