# Generated by Django 5.0.6 on 2024-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0009_boleta_banco_boleta_cargo_boleta_centro_de_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='correlativo',
            field=models.CharField(max_length=5, verbose_name='Correlativo'),
        ),
    ]
