# Generated by Django 5.0.6 on 2024-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_configuracionglobal_valorconfiguracionglobal_and_more'),
        ('planillas', '0010_alter_planilla_correlativo'),
        ('trabajadores', '0005_alter_trabajador_persona'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['contrato', 'planilla'], name='idx_boleta_contrato_planilla'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['visualizada', 'descargada'], name='idx_boleta_estado'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['trabajador'], name='idx_contrato_trabajador'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['clase_planilla', 'fuente_financiamiento'], name='idx_contrato_clase_fuente'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['fecha_ingreso', 'fecha_cese'], name='idx_contrato_fechas'),
        ),
        migrations.AddIndex(
            model_name='planilla',
            index=models.Index(fields=['periodo', 'estado'], name='idx_planilla_periodo_estado'),
        ),
        migrations.AddIndex(
            model_name='planilla',
            index=models.Index(fields=['clase_planilla', 'fuente_financiamiento'], name='idx_planilla_clase_fuente'),
        ),
    ]
