# Generated by Django 5.0.6 on 2024-06-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('usuarios', '0005_alter_persona_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ugel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.ugel', verbose_name='UGEL'),
        ),
    ]
