# Generated by Django 5.0.6 on 2024-06-27 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ugel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ugel', models.CharField(max_length=100, verbose_name='Nombre de Ugel')),
                ('nombre_corto', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre Corto')),
            ],
            options={
                'verbose_name': 'UGEL',
                'verbose_name_plural': 'UGELs',
                'db_table': 'ugel',
                'ordering': ['nombre_ugel'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CET', 'Carnet de extranjería'), ('PAS', 'Pasaporte')], default='DNI', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Número de Documento')),
                ('paterno', models.CharField(blank=True, max_length=45, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, max_length=45, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(blank=True, max_length=45, verbose_name='Nombres')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=45, verbose_name='Email')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='autenticacion.user')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['paterno', 'materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion_trabajador', models.CharField(blank=True, max_length=45, verbose_name='Relación del Trabajador')),
                ('documento_descuento', models.CharField(blank=True, max_length=45, verbose_name='Documento de Descuento')),
                ('numero_cuenta', models.CharField(blank=True, max_length=11, verbose_name='Número de Cuenta')),
                ('tipo_beneficiario', models.CharField(choices=[('JUDICIAL', 'Judicial'), ('TUTOR', 'Tutor')], default='JUDICIAL', max_length=10, verbose_name='Tipo de Beneficiario')),
                ('tipo_descuento', models.CharField(choices=[('MF', 'Monto Fijo'), ('DP', 'Descuento Porcentual')], default='MF', max_length=2, verbose_name='Tipo de Descuento')),
                ('descuento_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Descuento Fijo')),
                ('porcentaje_descuento', models.IntegerField(blank=True, null=True, verbose_name='Porcentaje de Descuento')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.banco', verbose_name='Banco')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='trabajadores.trabajador', verbose_name='Empleado')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'beneficiario',
                'ordering': ['id'],
            },
        ),
    ]
