# Generated by Django 5.0.6 on 2024-06-27 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'db_table': 'sexo',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Beneficiario',
                'verbose_name_plural': 'Tipos de Beneficiario',
                'db_table': 'tipo_beneficiario',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Descuento',
                'verbose_name_plural': 'Tipos de Descuento',
                'db_table': 'tipo_descuento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipo_documento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.sexo', verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo_beneficiario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipobeneficiario', verbose_name='Tipo de Beneficiario'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo_descuento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipodescuento', verbose_name='Tipo de Descuento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipodocumento', verbose_name='Tipo de Documento'),
        ),
    ]
