# Generated by Django 5.0.6 on 2024-06-27 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_sexo_tipobeneficiario_tipodescuento_tipodocumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipodocumento', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='tipobeneficiario',
            name='codigo',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='codigo',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código'),
        ),
    ]
