# Generated by Django 5.0.6 on 2024-06-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_persona_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipodocumento', verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
    ]
