# Generated by Django 5.0.6 on 2024-06-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('planillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto')),
                ('periodo_inicial', models.CharField(blank=True, max_length=6, verbose_name='Periodo Inicial')),
                ('periodo_final', models.CharField(blank=True, max_length=6, verbose_name='Periodo Final')),
                ('correlativo', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Correlativo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='planillas.contrato', verbose_name='Contrato')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Transacción del Trabajador',
                'verbose_name_plural': 'Transacciones de los Trabajadores',
                'db_table': 'transacciones_trabajadores',
                'ordering': ['transaccion', 'correlativo'],
            },
        ),
    ]
