# Generated by Django 5.0.6 on 2024-06-27 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HABER', 'Haber'), ('DESCUENTO', 'Descuento')], default='HABER', max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('SUELDO', 'Sueldo'), ('BONIFICACION', 'Bonificación'), ('DEDUCCION', 'Deducción'), ('BENEFICIOS_SOCIALES', 'Beneficios Sociales'), ('APORTE', 'Aporte'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('codigo', models.CharField(help_text='Código de Transacción', max_length=4, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transaccion',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto')),
                ('periodo_inicial', models.CharField(blank=True, max_length=6, verbose_name='Periodo Inicial')),
                ('periodo_final', models.CharField(blank=True, max_length=6, verbose_name='Periodo Final')),
                ('correlativo', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Correlativo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='trabajadores.trabajador', verbose_name='Trabajador')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacciones.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Transacción del Trabajador',
                'verbose_name_plural': 'Transacciones de los Trabajadores',
                'db_table': 'transacciones_trabajadores',
                'ordering': ['transaccion', 'correlativo'],
            },
        ),
    ]
