# Generated by Django 5.0.6 on 2024-06-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0003_contrato_delete_planillatrabajador'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacciontrabajador',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='transacciontrabajador',
            name='contrato',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='planillas.contrato', verbose_name='Contrato'),
            preserve_default=False,
        ),
    ]
