# Generated by Django 5.0.6 on 2024-07-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_comisionafp'),
        ('planillas', '0009_boleta_banco_boleta_cargo_boleta_centro_de_trabajo_and_more'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransaccionTrabajador',
            new_name='TransaccionContrato',
        ),
    ]
