# Generated by Django 5.0.6 on 2024-07-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_rename_transacciontrabajador_transaccioncontrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccioncontrato',
            options={'ordering': ['transaccion', 'secuencia'], 'verbose_name': 'Transacción del Trabajador', 'verbose_name_plural': 'Transacciones de los Trabajadores'},
        ),
        migrations.RenameField(
            model_name='transaccioncontrato',
            old_name='correlativo',
            new_name='secuencia',
        ),
    ]
