# Generated by Django 5.0.6 on 2024-06-27 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_afp', models.CharField(max_length=45, verbose_name='Nombre de AFP')),
            ],
            options={
                'verbose_name': 'AFP',
                'verbose_name_plural': 'AFPs',
                'db_table': 'afp',
                'ordering': ['nombre_afp'],
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=45, verbose_name='Nombre de Banco')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'banco',
                'ordering': ['nombre_banco'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=45, verbose_name='Nombre de Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['nombre_cargo'],
            },
        ),
        migrations.CreateModel(
            name='RegimenLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_regimen_laboral', models.CharField(max_length=45, verbose_name='Nombre de Régimen Laboral')),
            ],
            options={
                'verbose_name': 'Régimen Laboral',
                'verbose_name_plural': 'Regímenes Laborales',
                'db_table': 'regimen_laboral',
                'ordering': ['nombre_regimen_laboral'],
            },
        ),
        migrations.CreateModel(
            name='RegimenPensionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_regimen_pensionario', models.CharField(max_length=45, verbose_name='Nombre de Régimen Pensionario')),
            ],
            options={
                'verbose_name': 'Régimen Pensionario',
                'verbose_name_plural': 'Regímenes Pensionarios',
                'db_table': 'regimen_pensionario',
                'ordering': ['nombre_regimen_pensionario'],
            },
        ),
        migrations.CreateModel(
            name='TipoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_servidor', models.CharField(max_length=45, verbose_name='Nombre de Tipo de Servidor')),
            ],
            options={
                'verbose_name': 'Tipo de Servidor',
                'verbose_name_plural': 'Tipos de Servidores',
                'db_table': 'tipo_servidor',
                'ordering': ['nombre_tipo_servidor'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(choices=[('HAB', 'Habilitado'), ('LSG', 'Licencia sin goce'), ('LCG', 'Licencia con goce'), ('DES', 'Desabilitado'), ('VAC', 'Vacaciones')], default='HAB', max_length=20, null=True, verbose_name='Situación')),
                ('dias_licencia', models.IntegerField(blank=True, default=0, null=True, verbose_name='Días de Licencia')),
                ('fecha_ini_licencia', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Licencia')),
                ('tiempo_servicios', models.CharField(blank=True, max_length=6, verbose_name='Tiempo de Servicios')),
                ('dias_laborados', models.IntegerField(blank=True, default=30, null=True, verbose_name='Días Laborados')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='Fecha de Cese')),
                ('documento_contrato', models.CharField(blank=True, max_length=45, verbose_name='Documento de Contrato')),
                ('documento_cese', models.CharField(blank=True, max_length=45, verbose_name='Documento de Cese')),
                ('cuspp', models.CharField(blank=True, max_length=12, verbose_name='CUSPP')),
                ('fecha_afiliacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Afiliación')),
                ('fecha_devengue', models.DateField(blank=True, null=True, verbose_name='Fecha de Devengue')),
                ('codigo_nexus', models.CharField(blank=True, max_length=10, verbose_name='Código Nexus')),
                ('jornada_laboral', models.IntegerField(blank=True, null=True, verbose_name='Jornada Laboral')),
                ('descuentos_dias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Descuentos en Días')),
                ('descuentos_horas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Descuentos en Horas')),
                ('descuentos_minutos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Descuentos en Minutos')),
                ('leyenda_permanente', models.CharField(blank=True, max_length=45, verbose_name='Leyenda Permanente')),
                ('leyenda_mensual', models.CharField(blank=True, max_length=45, verbose_name='Leyenda Mensual')),
                ('numero_cuenta', models.CharField(blank=True, max_length=45, verbose_name='Número de Cuenta')),
                ('ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC')),
                ('afp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.afp', verbose_name='AFP')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.banco', verbose_name='Banco')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='trabajadores.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
