# Generated by Django 5.0.6 on 2024-06-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('trabajadores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='usuarios.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='regimen_pensionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.regimenpensionario', verbose_name='Régimen Pensionario'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='ugel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.ugel', verbose_name='UGEL'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['persona'], name='persona_idx'),
        ),
    ]
