# Generated by Django 5.0.6 on 2024-06-27 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='usuarios.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='regimen_laboral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.regimenlaboral', verbose_name='Régimen Laboral'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='regimen_pensionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.regimenpensionario', verbose_name='Régimen Pensionario'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.tiposervidor', verbose_name='Tipo de Servidor'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='ugel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ugel', verbose_name='UGEL'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['situacion'], name='situacion_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['fecha_ingreso'], name='fecha_ingreso_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['fecha_cese'], name='fecha_cese_idx'),
        ),
    ]
