# Generated by Django 5.0.6 on 2024-06-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre de Situación')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Situación',
                'verbose_name_plural': 'Situaciones',
                'db_table': 'situacion',
                'ordering': ['nombre'],
            },
        ),
    ]
