# Generated by Django 5.0.6 on 2024-06-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha_devengue',
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='tiempo_servicios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Servicios'),
        ),
    ]
