# Generated by Django 5.0.6 on 2024-06-27 19:18

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_situacion'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['id'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='situacion_idx',
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='fecha_ingreso_idx',
        ),
        migrations.RemoveIndex(
            model_name='trabajador',
            name='fecha_cese_idx',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='codigo_nexus',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='descuentos_dias',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='descuentos_horas',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='descuentos_minutos',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='dias_laborados',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='dias_licencia',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='documento_cese',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='documento_contrato',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha_cese',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha_ini_licencia',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='jornada_laboral',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='leyenda_mensual',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='leyenda_permanente',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='regimen_laboral',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='situacion',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='tipo_servidor',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['persona'], name='persona_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['ugel'], name='ugel_idx'),
        ),
        migrations.AlterModelTable(
            name='trabajador',
            table='trabajador',
        ),
    ]
