# Generated by Django 5.0.6 on 2024-07-01 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_alter_trabajador_persona'),
        ('usuarios', '0002_alter_persona_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='usuarios.persona', verbose_name='Persona'),
        ),
    ]
