# Generated by Django 5.0.6 on 2024-06-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_alter_trabajador_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trabajador',
            name='ugel_idx',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='ugel',
        ),
    ]
