# Generated by Django 5.0.6 on 2024-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_configuracionglobal_valorconfiguracionglobal_and_more'),
        ('trabajadores', '0005_alter_trabajador_persona'),
        ('usuarios', '0002_alter_persona_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trabajador',
            new_name='idx_trabajador_persona',
            old_name='persona_idx',
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['ugel'], name='idx_trabajador_ugel'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['estado'], name='idx_trabajador_estado'),
        ),
    ]
