# Generated by Django 5.0.6 on 2024-07-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planillas', '0009_boleta_banco_boleta_cargo_boleta_centro_de_trabajo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesosPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('planillas', models.ManyToManyField(blank=True, to='planillas.planilla')),
            ],
            options={
                'verbose_name': 'Proceso de Planilla',
                'verbose_name_plural': 'Procesos de Planillas',
            },
        ),
    ]
